# NOTE: Update and uncomment: `keystore`, `password`, and `unlock` fields.

chain = "./config/genesis.json"
identity = "node1.local"
# [verbosity]
# LvlError = 1, LvlWarn = 2, LvlInfo = 3, LvlDebug = 4, LvlTrace = 5
verbosity = 3
datadir = "./data/node_1"
# ancient = ""
keystore = "./data/keystore"
# "rpc.batchlimit" = 100
# "rpc.returndatalimit" = 100000
syncmode = "full"
# gcmode = "full"
# snapshot = true
# ethstats = ""

# Important otherwise we'd need to have a signer as part of block 0's validator set
devfakeauthor = true

# ["eth.requiredblocks"]

[p2p]
    maxpeers = 5
    port = 30303
    # maxpendpeers = 50
    # bind = "0.0.0.0"
    # nodiscover = false
    # nat = "any"
    # [p2p.discovery]
        # v5disc = false
        # bootnodes = []
        # bootnodesv4 = []
        # bootnodesv5 = []
        # static-nodes = []
        # trusted-nodes = []
        # dns = []

[heimdall]
    "bor.without" = true
    # url = "http://localhost:1317"
    # grpc-address = ""

[txpool]
    nolocals = true
    accountslots = 16
    globalslots = 131072
    accountqueue = 64
    globalqueue = 131072
    lifetime = "1h30m0s"
    # locals = []
    # journal = ""
    # rejournal = "1h0m0s"
    # pricelimit = 1
    # pricebump = 10

[miner]
    mine = true
    gaslimit = 30000000
    gasprice = "1000000"
    etherbase = "15d34AAf54267DB7D7c367839AAf71A00a2C6A65"
    # extradata = ""

[jsonrpc]
    ipcpath = "./ipc/node_1/bor.ipc"
    # ipcdisable = false
    # gascap = 50000000
    # txfeecap = 5.0
    [jsonrpc.http]
        enabled = true
        port = 8545
        host = "0.0.0.0"
        api = ["eth", "net", "web3", "txpool", "bor", "personal"]
        vhosts = ["*"]
        corsdomain = ["*"]
        # prefix = ""
    # [jsonrpc.ws]
        # enabled = false
        # port = 8546
        # prefix = ""
        # host = "localhost"
        # api = ["web3", "net"]
        # origins = ["*"]
    # [jsonrpc.graphql]
        # enabled = false
        # port = 0
        # prefix = ""
        # host = ""
        # vhosts = ["*"]
        # corsdomain = ["*"]
    # [jsonrpc.timeouts]
        # read = "30s"
        # write = "30s"
        # idle = "2m0s"

# [gpo]
#     blocks = 20
#     percentile = 60
#     maxprice = "5000000000000"
#     ignoreprice = "2"

[telemetry]
    metrics = false
    # expensive = false
    # prometheus-addr = ""
    # opencollector-endpoint = ""
    # [telemetry.influx]
        # influxdb = false
        # endpoint = ""
        # database = ""
        # username = ""
        # password = ""
        # influxdbv2 = false
        # token = ""
        # bucket = ""
        # organization = ""
    # [telemetry.influx.tags]

# [cache]
    # cache = 1024
    # gc = 25
    # snapshot = 10
    # database = 50
    # trie = 15
    # journal = "triecache"
    # rejournal = "1h0m0s"
    # noprefetch = false
    # preimages = false
    # txlookuplimit = 2350000
    # timeout = "1h0m0s"

[accounts]
    allow-insecure-unlock = true
    password = "./data/password.txt"
    unlock = ["15d34AAf54267DB7D7c367839AAf71A00a2C6A65", "90F79bf6EB2c4f870365E785982E1f101E93b906", "3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"]
    # lightkdf = true
    disable-bor-wallet = false

# [grpc]
    # addr = ":3131"

# [developer]
    # dev = false
    # period = 0
